// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"net/http"

	"github.com/dronm/meatshop/internal/models"
	"github.com/dronm/webapp"
)

func customerSalePlaceRoutes(api *webapp.Group) {
	api.POST(
		"/customer-sale-places",
		webapp.WithName("customerSalePlace.create"),
		webapp.WithPermission("customerSalePlace.create"),
		webapp.WithService("CustomerSalePlace", "Create"),
		webapp.WithBinder(webapp.InsertInputBinder[*models.CustomerSalePlace]()),
		webapp.WithSuccessCode(http.StatusCreated),
	)

	api.GET(
		"/customer-sale-places",
		webapp.WithName("customerSalePlace.list"),
		webapp.WithPermission("customerSalePlace.list"),
		webapp.WithService("CustomerSalePlace", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/customer-sale-places/{id}",
		webapp.WithName("customerSalePlace.detail"),
		webapp.WithPermission("customerSalePlace.detail"),
		webapp.WithService("CustomerSalePlace", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)

	api.PATCH(
		"/customer-sale-places/{id}",
		webapp.WithName("customerSalePlace.update"),
		webapp.WithPermission("customerSalePlace.update"),
		webapp.WithService("CustomerSalePlace", "Update"),
		webapp.WithBinder(webapp.UpdateByPathKeysBinder[*models.CustomerSalePlaceKey, *models.CustomerSalePlace]("id")),
	)

	api.DELETE(
		"/customer-sale-places/{id}",
		webapp.WithName("customerSalePlace.delete"),
		webapp.WithPermission("customerSalePlace.delete"),
		webapp.WithService("CustomerSalePlace", "Delete"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)
}
