// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"net/http"

	"github.com/dronm/meatshop/internal/models"
	"github.com/dronm/webapp"
)

func customerRoutes(api *webapp.Group) {
	api.POST(
		"/customer",
		webapp.WithName("customer.create"),
		webapp.WithPermission("customer.create"),
		webapp.WithService("Customer", "Create"),
		webapp.WithBinder(webapp.InsertInputBinder[*models.Customer]()),
		webapp.WithSuccessCode(http.StatusCreated),
	)

	api.GET(
		"/customer",
		webapp.WithName("customer.list"),
		webapp.WithPermission("customer.list"),
		webapp.WithService("Customer", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/customer/{id}",
		webapp.WithName("customer.detail"),
		webapp.WithPermission("customer.detail"),
		webapp.WithService("Customer", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)

	api.PATCH(
		"/customer/{id}",
		webapp.WithName("customer.update"),
		webapp.WithPermission("customer.update"),
		webapp.WithService("Customer", "Update"),
		webapp.WithBinder(webapp.UpdateByPathKeysBinder[*models.CustomerKey, *models.Customer]("id")),
	)

	api.DELETE(
		"/customer/{id}",
		webapp.WithName("customer.delete"),
		webapp.WithPermission("customer.delete"),
		webapp.WithService("Customer", "Delete"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)
}
