// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"github.com/dronm/webapp"
)

func maxInMessageRoutes(api *webapp.Group) {

	api.GET(
		"/max-in-messages",
		webapp.WithName("maxInMessage.list"),
		webapp.WithPermission("maxInMessage.list"),
		webapp.WithService("MaxInMessage", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/max-in-messages/{id}",
		webapp.WithName("maxInMessage.detail"),
		webapp.WithPermission("maxInMessage.detail"),
		webapp.WithService("MaxInMessage", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int64]("id")),
	)
}
