// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"github.com/dronm/webapp"
)

func maxOutMessageRoutes(api *webapp.Group) {

	api.GET(
		"/max-out-messages",
		webapp.WithName("maxOutMessage.list"),
		webapp.WithPermission("maxOutMessage.list"),
		webapp.WithService("MaxOutMessage", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/max-out-messages/{id}",
		webapp.WithName("maxOutMessage.detail"),
		webapp.WithPermission("maxOutMessage.detail"),
		webapp.WithService("MaxOutMessage", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int64]("id")),
	)
}
