// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"net/http"

	"github.com/dronm/meatshop/internal/models"
	"github.com/dronm/webapp"
)

func orderCalendarDayRoutes(api *webapp.Group) {
	api.POST(
		"/order-calendar-days",
		webapp.WithName("orderCalendarDay.create"),
		webapp.WithPermission("orderCalendarDay.create"),
		webapp.WithService("OrderCalendarDay", "Create"),
		webapp.WithBinder(webapp.InsertInputBinder[*models.OrderCalendarDay]()),
		webapp.WithSuccessCode(http.StatusCreated),
	)

	api.GET(
		"/order-calendar-days",
		webapp.WithName("orderCalendarDay.list"),
		webapp.WithPermission("orderCalendarDay.list"),
		webapp.WithService("OrderCalendarDay", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/order-calendar-days/{id}",
		webapp.WithName("orderCalendarDay.detail"),
		webapp.WithPermission("orderCalendarDay.detail"),
		webapp.WithService("OrderCalendarDay", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)

	api.PATCH(
		"/order-calendar-days/{id}",
		webapp.WithName("orderCalendarDay.update"),
		webapp.WithPermission("orderCalendarDay.update"),
		webapp.WithService("OrderCalendarDay", "Update"),
		webapp.WithBinder(webapp.UpdateByPathKeysBinder[*models.OrderCalendarDayKey, *models.OrderCalendarDay]("id")),
	)

	api.DELETE(
		"/order-calendar-days/{id}",
		webapp.WithName("orderCalendarDay.delete"),
		webapp.WithPermission("orderCalendarDay.delete"),
		webapp.WithService("OrderCalendarDay", "Delete"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)
}
