// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import (
	"net/http"

	"github.com/dronm/meatshop/internal/models"
	"github.com/dronm/webapp"
)

func productRoutes(api *webapp.Group) {
	api.POST(
		"/product",
		webapp.WithName("product.create"),
		webapp.WithPermission("product.create"),
		webapp.WithService("Product", "Create"),
		webapp.WithBinder(webapp.InsertInputBinder[*models.Product]()),
		webapp.WithSuccessCode(http.StatusCreated),
	)

	api.GET(
		"/product",
		webapp.WithName("product.list"),
		webapp.WithPermission("product.list"),
		webapp.WithService("Product", "List"),
		webapp.WithBinder(webapp.CollectionParamsBinder()),
	)

	api.GET(
		"/product/{id}",
		webapp.WithName("product.detail"),
		webapp.WithPermission("product.detail"),
		webapp.WithService("Product", "Detail"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)

	api.PATCH(
		"/product/{id}",
		webapp.WithName("product.update"),
		webapp.WithPermission("product.update"),
		webapp.WithService("Product", "Update"),
		webapp.WithBinder(webapp.UpdateByPathKeysBinder[*models.ProductKey, *models.Product]("id")),
	)

	api.DELETE(
		"/product/{id}",
		webapp.WithName("product.delete"),
		webapp.WithPermission("product.delete"),
		webapp.WithService("Product", "Delete"),
		webapp.WithBinder(webapp.PathValueBinder[int]("id")),
	)
}
