// Code generated by cmd/codegen. DO NOT EDIT.

package httpapi

import "github.com/dronm/webapp"

func registerGeneratedRoutes(api *webapp.Group) {
	customerRoutes(api)
	customerSalePlaceRoutes(api)
	maxUserRoutes(api)
	measureUnitRoutes(api)
	orderCalendarDayRoutes(api)
	productRoutes(api)
}
