// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	"github.com/dronm/modelbind"
	wmodels "github.com/dronm/webapp/models"
)

const customerSalePlaceRelation = "public.customer_sale_places"

// CustomerSalePlace describes an editable customer sale place reference entry.
type CustomerSalePlace struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Customer reference
	CustomerID int `json:"customer_id"`
	// Customer sale place display name.
	Name string `json:"name" required:"true"`
	// Sale place optional exact address.
	Address *string `json:"address"`
	// Customer KPP.
	Kpp *string `json:"kpp" maxLen:"10"`
	// Reference to 1C counterparty.
	Ref1C *Ref1c `json:"ref_1c"`
	// Whether the sale place is active.
	IsActive bool `json:"is_active" required:"true"`
}

func (m CustomerSalePlace) Relation() string {
	return customerSalePlaceRelation
}

func (m CustomerSalePlace) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

const customerSalePlaceListRelation = "public.customer_sale_places"

// CustomerSalePlaceList is the collection projection for Customer sale places.
type CustomerSalePlaceList struct {
	ID         int     `json:"id" primaryKey:"true"`
	CustomerID int     `json:"customer_id"`
	Name       string  `json:"name"`
	Address    *string `json:"address"`
	Kpp        *string `json:"kpp"`
	Ref1C      *Ref1c  `json:"ref_1c"`
	IsActive   bool    `json:"is_active"`
}

func (m CustomerSalePlaceList) Relation() string {
	return customerSalePlaceListRelation
}

func (m CustomerSalePlaceList) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// CustomerSalePlaceKey is used for detail, update, and delete WHERE clauses.
type CustomerSalePlaceKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m CustomerSalePlaceKey) Relation() string {
	return customerSalePlaceRelation
}

type UpdateCustomerSalePlaceRequest struct {
	ID    int
	Input modelbind.ModelInput[*CustomerSalePlace]
}
