// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	"github.com/dronm/modelbind"
	wmodels "github.com/dronm/webapp/models"
)

const customerRelation = "public.customers"

// Customer describes an editable customer reference entry.
type Customer struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Display name of the customer.
	Name string `json:"name" required:"true"`
	// Customer INN.
	Inn string `json:"inn" required:"true" maxLen:"12"`
	// Customer KPP.
	Kpp *string `json:"kpp" maxLen:"10"`
	// Reference to 1C counterparty.
	Ref1C    *Ref1c `json:"ref_1c"`
	IsActive bool   `json:"is_active" required:"true"`
	// Allows orders whose for_date is a holiday.
	AllowHolidayOrders bool `json:"allow_holiday_orders" required:"true"`
}

func (m Customer) Relation() string {
	return customerRelation
}

func (m Customer) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

const customerListRelation = "public.customers_list"

// CustomerList is the collection projection for customers.
type CustomerList struct {
	ID          int     `json:"id" primaryKey:"true"`
	Name        string  `json:"name"`
	Inn         string  `json:"inn"`
	Kpp         *string `json:"kpp"`
	Ref1CExists bool    `json:"ref_1c_exists"`
	IsActive    bool    `json:"is_active"`
}

func (m CustomerList) Relation() string {
	return customerListRelation
}

func (m CustomerList) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// CustomerKey is used for detail, update, and delete WHERE clauses.
type CustomerKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m CustomerKey) Relation() string {
	return customerRelation
}

type UpdateCustomerRequest struct {
	ID    int
	Input modelbind.ModelInput[*Customer]
}
