// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	wmodels "github.com/dronm/webapp/models"
	"time"
)

const maxInMessageRelation = "public.max_in_messages"

// MaxInMessage describes a read-only incoming MAX update.
type MaxInMessage struct {
	ID int64 `json:"id" primaryKey:"true" srvCalc:"true"`
	// MAX webhook update type.
	UpdateType string `json:"update_type" required:"true"`
	// Extracted MAX platform user ID, when available.
	MaxUserID *int64 `json:"max_user_id"`
	// Extracted MAX chat ID, when available.
	MaxChatID *int64 `json:"max_chat_id"`
	// Complete raw MAX webhook update.
	Message map[string]any `json:"message" required:"true"`
	// Time at which the webhook update was received.
	CreatedAt time.Time `json:"created_at" required:"true" srvCalc:"true"`
}

func (m MaxInMessage) Relation() string {
	return maxInMessageRelation
}

func (m MaxInMessage) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

const maxInMessageListRelation = "public.max_in_messages"

// MaxInMessageList is the collection projection for incoming MAX messages.
type MaxInMessageList struct {
	ID         int64     `json:"id" primaryKey:"true"`
	UpdateType string    `json:"update_type" required:"true"`
	MaxUserID  *int64    `json:"max_user_id"`
	MaxChatID  *int64    `json:"max_chat_id"`
	CreatedAt  time.Time `json:"created_at" required:"true"`
}

func (m MaxInMessageList) Relation() string {
	return maxInMessageListRelation
}

func (m MaxInMessageList) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// MaxInMessageKey is used for detail, update, and delete WHERE clauses.
type MaxInMessageKey struct {
	ID int64 `json:"id" primaryKey:"true" required:"true"`
}

func (m MaxInMessageKey) Relation() string {
	return maxInMessageRelation
}
