// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	wmodels "github.com/dronm/webapp/models"
	"time"
)

const maxOutMessageRelation = "public.max_out_messages"

// MaxOutMessage describes a read-only outgoing MAX message.
type MaxOutMessage struct {
	ID int64 `json:"id" primaryKey:"true" srvCalc:"true"`
	// MAX platform user ID.
	MaxUserID int64 `json:"max_user_id" required:"true"`
	// Complete MAX message request body.
	Message map[string]any `json:"message" required:"true"`
	// Application metadata associated with the message.
	Metadata map[string]any `json:"metadata" required:"true"`
	// Queue state: pending, sending, sent, or failed.
	Status string `json:"status" required:"true"`
	// Number of delivery attempts.
	AttemptCount int `json:"attempt_count" required:"true"`
	// Time at which the next delivery attempt may start.
	NextAttemptAt *time.Time `json:"next_attempt_at"`
	// Time at which a sender claimed the message.
	LockedAt *time.Time `json:"locked_at"`
	// Time at which the message was sent successfully.
	SentAt *time.Time `json:"sent_at"`
	// Time at which the outgoing message was queued.
	CreatedAt time.Time `json:"created_at" required:"true" srvCalc:"true"`
	// Last delivery error.
	ErrorStr *string `json:"error_str"`
}

func (m MaxOutMessage) Relation() string {
	return maxOutMessageRelation
}

func (m MaxOutMessage) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

const maxOutMessageListRelation = "public.max_out_messages_list"

// MaxOutMessageList is the collection projection for outgoing MAX messages.
type MaxOutMessageList struct {
	ID            int64      `json:"id" primaryKey:"true"`
	MaxUserID     int64      `json:"max_user_id" required:"true"`
	MaxUser       *Ref       `json:"max_user"`
	Status        string     `json:"status" required:"true"`
	AttemptCount  int        `json:"attempt_count" required:"true"`
	NextAttemptAt *time.Time `json:"next_attempt_at"`
	LockedAt      *time.Time `json:"locked_at"`
	SentAt        *time.Time `json:"sent_at"`
	CreatedAt     time.Time  `json:"created_at" required:"true"`
	ErrorStr      *string    `json:"error_str"`
}

func (m MaxOutMessageList) Relation() string {
	return maxOutMessageListRelation
}

func (m MaxOutMessageList) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// MaxOutMessageKey is used for detail, update, and delete WHERE clauses.
type MaxOutMessageKey struct {
	ID int64 `json:"id" primaryKey:"true" required:"true"`
}

func (m MaxOutMessageKey) Relation() string {
	return maxOutMessageRelation
}
