// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	"github.com/dronm/modelbind"
	wmodels "github.com/dronm/webapp/models"
)

const maxUserRelation = "public.max_users"

// MaxUser describes an editable MAX user reference entry.
type MaxUser struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Customer reference
	CustomerID *int `json:"customer_id"`
	// Default customer sale place for new MAX orders
	CustomerSalePlaceID *int `json:"customer_sale_place_id"`
	// MAX user ID
	MaxUserID int64 `json:"max_user_id" required:"true"`
	// Username supplied by the MAX platform; may be unavailable.
	Username *string `json:"username"`
	// MAX user avatar.
	AvatarURL *string `json:"avatar_url"`
	// Raw MAX user data.
	RawUser map[string]any `json:"raw_user" required:"true"`
	// Raw MAX user data containing photo information.
	RawUserWithPhoto *map[string]any `json:"raw_user_with_photo"`
	// Application display name shown for the customer user.
	AppUsername string `json:"app_username" required:"true"`
	// Whether the MAX user is active.
	IsActive bool `json:"is_active" required:"true"`
}

func (m MaxUser) Relation() string {
	return maxUserRelation
}

func (m MaxUser) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

const maxUserListRelation = "public.max_users_list"

// MaxUserList is the collection projection for MAX users.
type MaxUserList struct {
	ID                int            `json:"id" primaryKey:"true"`
	Customer          *Ref           `json:"customer"`
	CustomerSalePlace *Ref           `json:"customer_sale_place"`
	MaxUserID         int64          `json:"max_user_id"`
	Username          *string        `json:"username"`
	AppUsername       string         `json:"app_username"`
	AvatarURL         *string        `json:"avatar_url"`
	RawUser           map[string]any `json:"raw_user"`
	IsActive          bool           `json:"is_active"`
}

func (m MaxUserList) Relation() string {
	return maxUserListRelation
}

func (m MaxUserList) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// MaxUserKey is used for detail, update, and delete WHERE clauses.
type MaxUserKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m MaxUserKey) Relation() string {
	return maxUserRelation
}

type UpdateMaxUserRequest struct {
	ID    int
	Input modelbind.ModelInput[*MaxUser]
}
