// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	wmodels "github.com/dronm/webapp/models"
)

const orderItemRelation = "public.order_items"

// OrderItem describes a line of a order document.
type OrderItem struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Line number within the document.
	LineNum int `json:"line_num" required:"true"`
	// Parent order document.
	OrderID int `json:"order_id" required:"true"`
	// Product.
	ProductID int `json:"product_id" required:"true"`
	// Measurement unit.
	MeasureUnitID int `json:"measure_unit_id" required:"true"`
	// Ordered product quantity.
	QuantRequired float64 `json:"quant_required" required:"true"`
	// Product quantity.
	Quant float64 `json:"quant" required:"true"`
	// Unit price.
	Price *float64 `json:"price"`
	// Line amount with VAT.
	Amount *float64 `json:"amount"`
	// Line VAT percent.
	VatPercent *float64 `json:"vat_percent"`
	// Line VAT amount.
	VatAmount *float64 `json:"vat_amount"`
	// Line use marking flag.
	UseMarking bool `json:"use_marking" required:"true"`
}

func (m OrderItem) Relation() string {
	return orderItemRelation
}

func (m OrderItem) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// OrderItemKey is used for detail, update, and delete WHERE clauses.
type OrderItemKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m OrderItemKey) Relation() string {
	return orderItemRelation
}
