// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	"time"

	"github.com/dronm/modelbind"
	wmodels "github.com/dronm/webapp/models"
)

const orderRelation = "public.orders"

// Order describes an order document header.
type Order struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Optimistic concurrency version.
	Version int64 `json:"version" required:"true" srvCalc:"true"`
	// Order for what date.
	ForDate  time.Time `json:"for_date" required:"true"`
	Number1C *string   `json:"number_1c"`
	// Reference to 1c object.
	Ref1C *Ref1c `json:"ref_1c"`
	// Reference to 1c shipment object.
	ShipmentRef1C *Ref1c `json:"shipment_ref_1c"`
	// Customer reference
	CustomerID int `json:"customer_id" required:"true"`
	// Customer sale place reference
	CustomerSalePlaceID int `json:"customer_sale_place_id" required:"true"`
	// Customer user reference
	CustomerUserID *int `json:"customer_user_id"`
	// Order status reference
	StatusID        *int    `json:"status_id"`
	CommentCustomer *string `json:"comment_customer"`
	CommentAdmin    *string `json:"comment_admin"`
}

func (m Order) Relation() string {
	return orderRelation
}

func (m Order) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

const orderListRelation = "public.orders_list"

// OrderList is the collection projection for orders.
type OrderList struct {
	ID                int       `json:"id" primaryKey:"true"`
	Number1C          *string   `json:"number_1c"`
	ForDate           time.Time `json:"for_date"`
	Ref1C             *Ref1c    `json:"ref_1c"`
	ShipmentRef1C     *Ref1c    `json:"shipment_ref_1c"`
	CustomerID        int       `json:"customer_id"`
	Customer          *Ref      `json:"customer"`
	CustomerSalePlace *Ref      `json:"customer_sale_place"`
	CustomerUser      *Ref      `json:"customer_user"`
	Status            *Ref      `json:"status"`
	CommentCustomer   *string   `json:"comment_customer"`
	CommentAdmin      *string   `json:"comment_admin"`
}

func (m OrderList) Relation() string {
	return orderListRelation
}

func (m OrderList) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// OrderKey is used for detail, update, and delete WHERE clauses.
type OrderKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m OrderKey) Relation() string {
	return orderRelation
}

type UpdateOrderRequest struct {
	ID    int
	Input modelbind.ModelInput[*Order]
}
