// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	"time"

	"github.com/dronm/modelbind"
	wmodels "github.com/dronm/webapp/models"
)

const orderCalendarDayRelation = "public.order_calendar_days"

// OrderCalendarDay describes an order calendar override.
type OrderCalendarDay struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Business calendar date.
	CalendarDate time.Time `json:"calendar_date" required:"true"`
	// Whether the date is a holiday; false marks a working-day override.
	IsHoliday bool `json:"is_holiday" required:"true"`
	// Optional holiday or working-day override description.
	Name *string `json:"name"`
}

func (m OrderCalendarDay) Relation() string {
	return orderCalendarDayRelation
}

func (m OrderCalendarDay) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// OrderCalendarDayKey is used for detail, update, and delete WHERE clauses.
type OrderCalendarDayKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m OrderCalendarDayKey) Relation() string {
	return orderCalendarDayRelation
}

type UpdateOrderCalendarDayRequest struct {
	ID    int
	Input modelbind.ModelInput[*OrderCalendarDay]
}
