// Code generated by cmd/codegen. DO NOT EDIT.

package models

import (
	"github.com/dronm/modelbind"
	wmodels "github.com/dronm/webapp/models"
)

const productRelation = "public.products"

// Product describes an editable product reference entry.
type Product struct {
	ID int `json:"id" primaryKey:"true" srvCalc:"true"`
	// Parent product group.
	ParentID *int `json:"parent_id"`
	// Display name of the product.
	Name string `json:"name" required:"true" maxLen:"500"`
	// Full name of the product.
	Description *string `json:"description"`
	// Reference to 1C element.
	Ref1C *Ref1c `json:"ref_1c"`
	// Sort order.
	SortOrder int `json:"sort_order" required:"true"`
	// Base measurement unit of the product.
	MeasureUnitID *int `json:"measure_unit_id"`
	// Indicates whether the product is a group.
	IsGroup bool `json:"is_group" required:"true"`
	// Indicates whether the product is active.
	IsActive bool `json:"is_active" required:"true"`
}

func (m Product) Relation() string {
	return productRelation
}

func (m Product) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

const productListRelation = "public.products_list"

// ProductList is the collection projection for products.
type ProductList struct {
	ID            int    `json:"id" primaryKey:"true"`
	ParentID      *int   `json:"parent_id"`
	Name          string `json:"name" required:"true"`
	MeasureUnitID *int   `json:"measure_unit_id"`
	Ref1C         *Ref1c `json:"ref_1c"`
	MeasureUnit   *Ref   `json:"measure_unit"`
	SortOrder     int    `json:"sort_order" required:"true"`
	IsGroup       bool   `json:"is_group" required:"true"`
	IsActive      bool   `json:"is_active" required:"true"`
}

func (m ProductList) Relation() string {
	return productListRelation
}

func (m ProductList) CollectionAgg() any {
	return &wmodels.TotCount{TotCount: 0}
}

// ProductKey is used for detail, update, and delete WHERE clauses.
type ProductKey struct {
	ID int `json:"id" primaryKey:"true" required:"true"`
}

func (m ProductKey) Relation() string {
	return productRelation
}

type UpdateProductRequest struct {
	ID    int
	Input modelbind.ModelInput[*Product]
}
