-- Code generated by cmd/codegen. Review before applying.

BEGIN;

CREATE TABLE public.customer_sale_places (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	customer_id integer REFERENCES public.customers(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	name text NOT NULL,
	address text,
	is_active boolean NOT NULL DEFAULT true
);

COMMENT ON TABLE public.customer_sale_places IS 'Customer sale place reference data.';
COMMENT ON COLUMN public.customer_sale_places.customer_id IS 'Customer reference';
COMMENT ON COLUMN public.customer_sale_places.name IS 'Customer sale place display name.';
COMMENT ON COLUMN public.customer_sale_places.address IS 'Sale place optional exact address.';
COMMENT ON COLUMN public.customer_sale_places.is_active IS 'Whether the sale place is active.';

CREATE UNIQUE INDEX customer_sale_places_customer_name_idx
	ON public.customer_sale_places USING btree (customer_id, lower(name));

WITH required(code, description) AS (
	VALUES
		('customerSalePlace.create', 'Create Customer sale place'),
		('customerSalePlace.list', 'Просмотр списка точек продаж'),
		('customerSalePlace.detail', 'Просмотр точки продажи'),
		('customerSalePlace.update', 'Изменение точки продажи'),
		('customerSalePlace.delete', 'Удаление точки продажи')
)
INSERT INTO public.permissions (code, description)
SELECT required.code, required.description
FROM required
ON CONFLICT (code) DO UPDATE
SET description = EXCLUDED.description;

WITH roles(role_id) AS (
	VALUES
		('admin'::public.role_types)
), required(permission_code) AS (
	VALUES
		('customerSalePlace.create'),
		('customerSalePlace.list'),
		('customerSalePlace.detail'),
		('customerSalePlace.update'),
		('customerSalePlace.delete')
)
INSERT INTO public.role_permissions (role_id, permission_code)
SELECT roles.role_id, required.permission_code
FROM roles
CROSS JOIN required
ON CONFLICT DO NOTHING;

INSERT INTO public.application_routes (
	name,
	path,
	descr,
	section,
	icon,
	menu_available,
	is_active
)
VALUES (
	'customerSalePlaces',
	'/customer-sale-places',
	'Точки продажи',
	'Справочники',
	'pi pi-warehouse',
	true,
	true
)
ON CONFLICT (name) DO UPDATE
SET
	path = EXCLUDED.path,
	descr = EXCLUDED.descr,
	section = EXCLUDED.descr,
	icon = EXCLUDED.icon,
	menu_available = EXCLUDED.menu_available,
	is_active = true;

INSERT INTO public.main_menus (
	role_id,
	caption,
	icon,
	sort_order,
	is_active
)
SELECT
	'admin'::public.role_types,
	'Точки продажи',
	NULL,
	40,
	true
WHERE NOT EXISTS (
	SELECT 1
	FROM public.main_menus AS existing
	WHERE existing.role_id = 'admin'::public.role_types
		AND existing.user_id IS NULL
		AND existing.parent_id IS NULL
		AND existing.caption = 'Точки продажи'
);

UPDATE public.main_menus
SET
	icon = NULL,
	sort_order = 40,
	is_active = true
WHERE role_id = 'admin'::public.role_types
	AND user_id IS NULL
	AND parent_id IS NULL
	AND caption = 'Точки продажи';

UPDATE public.main_menus AS existing
SET
	parent_id = (
		SELECT parent.id
		FROM public.main_menus AS parent
		WHERE parent.role_id = 'admin'::public.role_types
			AND parent.user_id IS NULL
			AND parent.parent_id IS NULL
			AND parent.caption = 'Точки продажи'
		ORDER BY parent.id
		LIMIT 1
	),
	caption = 'Точки продажи',
	icon = NULL,
	sort_order = 10,
	is_active = true
FROM public.application_routes AS route
WHERE route.name = 'customerSalePlaces'
	AND existing.role_id = 'admin'::public.role_types
	AND existing.user_id IS NULL
	AND existing.route_id = route.id
	AND EXISTS (
		SELECT 1
		FROM public.main_menus AS parent
		WHERE parent.role_id = 'admin'::public.role_types
			AND parent.user_id IS NULL
			AND parent.parent_id IS NULL
			AND parent.caption = 'Точки продажи'
	)
;

INSERT INTO public.main_menus (
	role_id,
	parent_id,
	caption,
	route_id,
	icon,
	sort_order,
	is_active
)
SELECT
	'admin'::public.role_types,
	parent.id,
	'Точки продажи',
	route.id,
	NULL,
	10,
	true
FROM public.application_routes AS route
JOIN LATERAL (
	SELECT item.id
	FROM public.main_menus AS item
	WHERE item.role_id = 'admin'::public.role_types
		AND item.user_id IS NULL
		AND item.parent_id IS NULL
		AND item.caption = 'Точки продажи'
	ORDER BY item.id
	LIMIT 1
) AS parent ON true
WHERE route.name = 'customerSalePlaces'
	AND NOT EXISTS (
		SELECT 1
		FROM public.main_menus AS existing
		WHERE existing.role_id = 'admin'::public.role_types
			AND existing.user_id IS NULL
			AND existing.route_id = route.id
	);

COMMIT;
