-- Code generated by cmd/codegen. Review before applying.

BEGIN;

CREATE TABLE public.products (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	parent_id integer REFERENCES public.products(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	name varchar(500) NOT NULL,
	description text,
	ref_1c text,
	sort_order integer NOT NULL DEFAULT 0,
	measure_unit_id integer NOT NULL REFERENCES public.measure_units(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	is_group boolean NOT NULL DEFAULT false,
	is_active boolean NOT NULL DEFAULT true,
	CHECK (btrim(name) <> '')
);

COMMENT ON TABLE public.products IS 'Product reference data.';
COMMENT ON COLUMN public.products.parent_id IS 'Parent product group.';
COMMENT ON COLUMN public.products.name IS 'Display name of the product.';
COMMENT ON COLUMN public.products.description IS 'Full name of the product.';
COMMENT ON COLUMN public.products.ref_1c IS 'Reference to 1c element';
COMMENT ON COLUMN public.products.measure_unit_id IS 'Base measurement unit of the product.';

ALTER TABLE public.order_items
	ADD CONSTRAINT order_items_product_id_fkey
	FOREIGN KEY (product_id) REFERENCES public.products(id)
	ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE INDEX products_name_idx
	ON public.products USING btree (lower(name));

CREATE INDEX products_ref_1c_idx
	ON public.products USING btree (ref_1c);

WITH required(code, description) AS (
	VALUES
		('product.create', 'Создание продукции'),
		('product.list', 'Просмотр списка продукции'),
		('product.detail', 'Просмотр продукции'),
		('product.update', 'Изменение продукции'),
		('product.delete', 'Удаление продукции')
)
INSERT INTO public.permissions (code, description)
SELECT required.code, required.description
FROM required
ON CONFLICT (code) DO UPDATE
SET description = EXCLUDED.description;

WITH roles(role_id) AS (
	VALUES
		('admin'::public.role_types)
), required(permission_code) AS (
	VALUES
		('product.create'),
		('product.list'),
		('product.detail'),
		('product.update'),
		('product.delete')
)
INSERT INTO public.role_permissions (role_id, permission_code)
SELECT roles.role_id, required.permission_code
FROM roles
CROSS JOIN required
ON CONFLICT DO NOTHING;

INSERT INTO public.application_routes (
	name,
	path,
	descr,
	section,
	icon,
	menu_available,
	is_active
)
VALUES (
	'products',
	'/product',
	'Продукция',
	'Справочники',
	'pi pi-list',
	true,
	true
)
ON CONFLICT (name) DO UPDATE
SET
	path = EXCLUDED.path,
	descr = EXCLUDED.descr,
	section = EXCLUDED.descr,
	icon = EXCLUDED.icon,
	menu_available = EXCLUDED.menu_available,
	is_active = true;

INSERT INTO public.main_menus (
	role_id,
	caption,
	icon,
	sort_order,
	is_active
)
SELECT
	'admin'::public.role_types,
	'Продукция',
	NULL,
	40,
	true
WHERE NOT EXISTS (
	SELECT 1
	FROM public.main_menus AS existing
	WHERE existing.role_id = 'admin'::public.role_types
		AND existing.user_id IS NULL
		AND existing.parent_id IS NULL
		AND existing.caption = 'Продукция'
);

UPDATE public.main_menus
SET
	icon = NULL,
	sort_order = 40,
	is_active = true
WHERE role_id = 'admin'::public.role_types
	AND user_id IS NULL
	AND parent_id IS NULL
	AND caption = 'Продукция';

UPDATE public.main_menus AS existing
SET
	parent_id = (
		SELECT parent.id
		FROM public.main_menus AS parent
		WHERE parent.role_id = 'admin'::public.role_types
			AND parent.user_id IS NULL
			AND parent.parent_id IS NULL
			AND parent.caption = 'Продукция'
		ORDER BY parent.id
		LIMIT 1
	),
	caption = 'Продукция',
	icon = NULL,
	sort_order = 10,
	is_active = true
FROM public.application_routes AS route
WHERE route.name = 'products'
	AND existing.role_id = 'admin'::public.role_types
	AND existing.user_id IS NULL
	AND existing.route_id = route.id
	AND EXISTS (
		SELECT 1
		FROM public.main_menus AS parent
		WHERE parent.role_id = 'admin'::public.role_types
			AND parent.user_id IS NULL
			AND parent.parent_id IS NULL
			AND parent.caption = 'Продукция'
	)
;

INSERT INTO public.main_menus (
	role_id,
	parent_id,
	caption,
	route_id,
	icon,
	sort_order,
	is_active
)
SELECT
	'admin'::public.role_types,
	parent.id,
	'Продукция',
	route.id,
	NULL,
	10,
	true
FROM public.application_routes AS route
JOIN LATERAL (
	SELECT item.id
	FROM public.main_menus AS item
	WHERE item.role_id = 'admin'::public.role_types
		AND item.user_id IS NULL
		AND item.parent_id IS NULL
		AND item.caption = 'Продукция'
	ORDER BY item.id
	LIMIT 1
) AS parent ON true
WHERE route.name = 'products'
	AND NOT EXISTS (
		SELECT 1
		FROM public.main_menus AS existing
		WHERE existing.role_id = 'admin'::public.role_types
			AND existing.user_id IS NULL
			AND existing.route_id = route.id
	);

COMMIT;
