BEGIN;

ALTER TABLE public.order_calendar_days
	ADD COLUMN id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL;

ALTER TABLE public.order_calendar_days
	DROP CONSTRAINT order_calendar_days_pkey,
	ADD CONSTRAINT order_calendar_days_pkey PRIMARY KEY (id),
	ADD CONSTRAINT order_calendar_days_calendar_date_key UNIQUE (calendar_date);

COMMENT ON COLUMN public.order_calendar_days.id IS
	'Generated API key for an order calendar override.';

WITH required(code, description) AS (
	VALUES
		('orderCalendarDay.create', 'Создание дня календаря заказов'),
		('orderCalendarDay.list', 'Просмотр календаря заказов'),
		('orderCalendarDay.detail', 'Просмотр дня календаря заказов'),
		('orderCalendarDay.update', 'Изменение дня календаря заказов'),
		('orderCalendarDay.delete', 'Удаление дня календаря заказов')
)
INSERT INTO public.permissions (code, description)
SELECT required.code, required.description
FROM required
ON CONFLICT (code) DO UPDATE
SET description = EXCLUDED.description;

WITH required(permission_code) AS (
	VALUES
		('orderCalendarDay.create'),
		('orderCalendarDay.list'),
		('orderCalendarDay.detail'),
		('orderCalendarDay.update'),
		('orderCalendarDay.delete')
)
INSERT INTO public.role_permissions (role_id, permission_code)
SELECT 'admin'::public.role_types, required.permission_code
FROM required
ON CONFLICT DO NOTHING;

WITH aliases(table_name, column_name, column_alias) AS (
	VALUES
		('order_calendar_days', 'id', 'ID'),
		('order_calendar_days', 'calendar_date', 'Дата календаря'),
		('order_calendar_days', 'is_holiday', 'Выходной день'),
		('order_calendar_days', 'name', 'Описание')
)
INSERT INTO public.audit_column_aliases (
	table_name,
	column_name,
	column_alias,
	is_active
)
SELECT
	aliases.table_name,
	aliases.column_name,
	aliases.column_alias,
	true
FROM aliases
ON CONFLICT (table_name, column_name) DO UPDATE
SET
	column_alias = EXCLUDED.column_alias,
	is_active = true;

DROP TRIGGER IF EXISTS audit_log_order_calendar_days
	ON public.order_calendar_days;

CREATE TRIGGER audit_log_order_calendar_days
AFTER INSERT OR UPDATE OR DELETE ON public.order_calendar_days
FOR EACH ROW EXECUTE FUNCTION public.audit_log_process();

COMMIT;
