
BEGIN;

	CREATE TABLE public.order_statuses (
		id int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
		code text NOT NULL,
		name text NOT NULL,
		sort_order int NOT NULL,
		is_final boolean NOT NULL DEFAULT FALSE
	);

	INSERT INTO public.order_statuses
	(code, name, sort_order, is_final)
	VALUES
	('new', 'Новый', 10, FALSE),
	('accepted', '', 20, FALSE),
	('processing', 'В обработке', 40, FALSE),
	('approved', 'Согласован', 50, FALSE),
	('completed', 'Выполнен', 60, TRUE),
	('cancelled', 'Отменен', 60, TRUE);

COMMIT;
