BEGIN;

CREATE TABLE public.ra_products (
	id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	effective_at timestamptz NOT NULL,
	created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	recorder_type text NOT NULL,
	recorder_id bigint NOT NULL,
	customer_id integer NOT NULL REFERENCES public.customers(id),
	customer_sale_place_id integer NOT NULL REFERENCES public.customer_sale_places(id),
	product_id integer NOT NULL REFERENCES public.products(id),
	measure_unit_id integer NOT NULL REFERENCES public.measure_units(id),
	quant_required numeric(19, 4) NOT NULL,
	quant numeric(19, 4) NOT NULL,
	CONSTRAINT ra_products_recorder_type_chk CHECK (btrim(recorder_type) <> ''),
	CONSTRAINT ra_products_facts_chk CHECK (quant_required <> 0 OR quant <> 0)
);

COMMENT ON TABLE public.ra_products IS 'Authoritative immutable action ledger for the products accumulation register.';
COMMENT ON COLUMN public.ra_products.effective_at IS 'Business instant at which the order demand takes effect.';
COMMENT ON COLUMN public.ra_products.created_at IS 'Instant when the register action row was created.';
COMMENT ON COLUMN public.ra_products.recorder_type IS 'Application-level type/name of the source document that produced the action.';
COMMENT ON COLUMN public.ra_products.recorder_id IS 'Identifier of the source document that produced the action.';
COMMENT ON COLUMN public.ra_products.quant_required IS 'Signed required product quantity accumulated by the register.';
COMMENT ON COLUMN public.ra_products.quant IS 'Signed actual product quantity accumulated by the register.';

CREATE INDEX ra_products_recorder_idx
	ON public.ra_products (recorder_type, recorder_id);

CREATE INDEX ra_products_effective_at_idx
	ON public.ra_products (effective_at);

CREATE INDEX ra_products_balance_idx
	ON public.ra_products (
		customer_id,
		customer_sale_place_id,
		product_id,
		measure_unit_id,
		effective_at,
		id
	);

CREATE TABLE public.rg_products (
	period_start date NOT NULL,
	customer_id integer NOT NULL REFERENCES public.customers(id),
	customer_sale_place_id integer NOT NULL REFERENCES public.customer_sale_places(id),
	product_id integer NOT NULL REFERENCES public.products(id),
	measure_unit_id integer NOT NULL REFERENCES public.measure_units(id),
	quant_required numeric(19, 4) NOT NULL,
	quant numeric(19, 4) NOT NULL,
	CONSTRAINT rg_products_pkey PRIMARY KEY (
		customer_id,
		customer_sale_place_id,
		product_id,
		measure_unit_id,
		period_start
	)
);

COMMENT ON TABLE public.rg_products IS 'Monthly net turnover of the products register. Rows are period deltas, not cumulative balances.';
COMMENT ON COLUMN public.rg_products.period_start IS 'First local calendar date of the aggregation month in the configured business time zone.';

CREATE INDEX rg_products_start_idx
	ON public.rg_products (period_start);

CREATE TABLE public.rg_products_current (
	customer_id integer NOT NULL REFERENCES public.customers(id),
	customer_sale_place_id integer NOT NULL REFERENCES public.customer_sale_places(id),
	product_id integer NOT NULL REFERENCES public.products(id),
	measure_unit_id integer NOT NULL REFERENCES public.measure_units(id),
	quant_required numeric(19, 4) NOT NULL,
	quant numeric(19, 4) NOT NULL,
	CONSTRAINT rg_products_current_pkey PRIMARY KEY (
		customer_id,
		customer_sale_place_id,
		product_id,
		measure_unit_id
	)
);

COMMENT ON TABLE public.rg_products_current IS 'Fast current accumulated totals of the products register.';

CREATE OR REPLACE FUNCTION public.rg_products_apply_delta(
	in_effective_at timestamptz,
	in_customer_id integer,
	in_customer_sale_place_id integer,
	in_product_id integer,
	in_measure_unit_id integer,
	in_delta_quant_required numeric(19, 4),
	in_delta_quant numeric(19, 4)
)
RETURNS void
LANGUAGE plpgsql
AS $function$
DECLARE
	v_period_start date;
BEGIN
	IF in_delta_quant_required = 0 AND in_delta_quant = 0 THEN
		RETURN;
	END IF;

	v_period_start := public.register_month_start(in_effective_at);

	INSERT INTO public.rg_products (
		period_start,
		customer_id,
		customer_sale_place_id,
		product_id,
		measure_unit_id,
		quant_required,
		quant
	)
	VALUES (
		v_period_start,
		in_customer_id,
		in_customer_sale_place_id,
		in_product_id,
		in_measure_unit_id,
		in_delta_quant_required,
		in_delta_quant
	)
	ON CONFLICT (
		customer_id,
		customer_sale_place_id,
		product_id,
		measure_unit_id,
		period_start
	)
	DO UPDATE
	SET
		quant_required = rg_products.quant_required + EXCLUDED.quant_required,
		quant = rg_products.quant + EXCLUDED.quant;

	DELETE FROM public.rg_products
	WHERE period_start = v_period_start
		AND customer_id = in_customer_id
		AND customer_sale_place_id = in_customer_sale_place_id
		AND product_id = in_product_id
		AND measure_unit_id = in_measure_unit_id
		AND quant_required = 0
		AND quant = 0;

	INSERT INTO public.rg_products_current (
		customer_id,
		customer_sale_place_id,
		product_id,
		measure_unit_id,
		quant_required,
		quant
	)
	VALUES (
		in_customer_id,
		in_customer_sale_place_id,
		in_product_id,
		in_measure_unit_id,
		in_delta_quant_required,
		in_delta_quant
	)
	ON CONFLICT (
		customer_id,
		customer_sale_place_id,
		product_id,
		measure_unit_id
	)
	DO UPDATE
	SET
		quant_required = rg_products_current.quant_required + EXCLUDED.quant_required,
		quant = rg_products_current.quant + EXCLUDED.quant;

	DELETE FROM public.rg_products_current
	WHERE customer_id = in_customer_id
		AND customer_sale_place_id = in_customer_sale_place_id
		AND product_id = in_product_id
		AND measure_unit_id = in_measure_unit_id
		AND quant_required = 0
		AND quant = 0;
END;
$function$;

CREATE OR REPLACE FUNCTION public.ra_products_process()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
	IF TG_OP = 'INSERT' THEN
		PERFORM public.rg_products_apply_delta(
			NEW.effective_at,
			NEW.customer_id,
			NEW.customer_sale_place_id,
			NEW.product_id,
			NEW.measure_unit_id,
			NEW.quant_required,
			NEW.quant
		);
		RETURN NEW;
	END IF;

	IF TG_OP = 'DELETE' THEN
		PERFORM public.rg_products_apply_delta(
			OLD.effective_at,
			OLD.customer_id,
			OLD.customer_sale_place_id,
			OLD.product_id,
			OLD.measure_unit_id,
			-OLD.quant_required,
			-OLD.quant
		);
		RETURN OLD;
	END IF;

	RAISE EXCEPTION 'Unsupported operation % on ra_products', TG_OP;
END;
$function$;

CREATE TRIGGER ra_products_process_trigger
	AFTER INSERT OR DELETE
	ON public.ra_products
	FOR EACH ROW
	EXECUTE FUNCTION public.ra_products_process();

CREATE OR REPLACE FUNCTION public.ra_products_reject_update()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
	RAISE EXCEPTION 'ra_products rows are immutable; delete old register actions and insert replacement actions instead'
		USING ERRCODE = '55000';
END;
$function$;

CREATE TRIGGER ra_products_reject_update_trigger
	BEFORE UPDATE
	ON public.ra_products
	FOR EACH ROW
	EXECUTE FUNCTION public.ra_products_reject_update();

CREATE OR REPLACE FUNCTION public.ra_products_add_act(
	in_effective_at timestamptz,
	in_recorder_type text,
	in_recorder_id bigint,
	in_customer_id integer,
	in_customer_sale_place_id integer,
	in_product_id integer,
	in_measure_unit_id integer,
	in_quant_required numeric(19, 4),
	in_quant numeric(19, 4)
)
RETURNS bigint
LANGUAGE plpgsql
AS $function$
DECLARE
	v_id bigint;
BEGIN
	INSERT INTO public.ra_products (
		effective_at,
		recorder_type,
		recorder_id,
		customer_id,
		customer_sale_place_id,
		product_id,
		measure_unit_id,
		quant_required,
		quant
	)
	VALUES (
		in_effective_at,
		in_recorder_type,
		in_recorder_id,
		in_customer_id,
		in_customer_sale_place_id,
		in_product_id,
		in_measure_unit_id,
		in_quant_required,
		in_quant
	)
	RETURNING id INTO v_id;

	RETURN v_id;
END;
$function$;

COMMENT ON FUNCTION public.ra_products_add_act(timestamptz, text, bigint, integer, integer, integer, integer, numeric, numeric) IS 'Adds one immutable products register action and returns its action id.';

CREATE OR REPLACE FUNCTION public.ra_products_remove_acts(
	in_recorder_type text,
	in_recorder_id bigint
)
RETURNS bigint
LANGUAGE sql
AS $function$
	WITH deleted AS (
		DELETE FROM public.ra_products
		WHERE recorder_type = in_recorder_type
			AND recorder_id = in_recorder_id
		RETURNING 1
	)
	SELECT count(*)::bigint
	FROM deleted;
$function$;

COMMENT ON FUNCTION public.ra_products_remove_acts(text, bigint) IS 'Removes all products register actions written by one source recorder and returns the number of removed actions.';

CREATE OR REPLACE FUNCTION public.rg_products_rebuild()
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
	TRUNCATE TABLE public.rg_products, public.rg_products_current;

	INSERT INTO public.rg_products (
		period_start,
		customer_id,
		customer_sale_place_id,
		product_id,
		measure_unit_id,
		quant_required,
		quant
	)
	SELECT
		public.register_month_start(action.effective_at),
		action.customer_id,
		action.customer_sale_place_id,
		action.product_id,
		action.measure_unit_id,
		SUM(action.quant_required)::numeric(19, 4),
		SUM(action.quant)::numeric(19, 4)
	FROM public.ra_products AS action
	GROUP BY
		public.register_month_start(action.effective_at),
		action.customer_id,
		action.customer_sale_place_id,
		action.product_id,
		action.measure_unit_id
	HAVING SUM(action.quant_required) <> 0 OR SUM(action.quant) <> 0;

	INSERT INTO public.rg_products_current (
		customer_id,
		customer_sale_place_id,
		product_id,
		measure_unit_id,
		quant_required,
		quant
	)
	SELECT
		action.customer_id,
		action.customer_sale_place_id,
		action.product_id,
		action.measure_unit_id,
		SUM(action.quant_required)::numeric(19, 4),
		SUM(action.quant)::numeric(19, 4)
	FROM public.ra_products AS action
	GROUP BY
		action.customer_id,
		action.customer_sale_place_id,
		action.product_id,
		action.measure_unit_id
	HAVING SUM(action.quant_required) <> 0 OR SUM(action.quant) <> 0;
END;
$function$;

COMMENT ON FUNCTION public.rg_products_rebuild() IS 'Rebuilds all products register aggregates from the authoritative ra_products ledger.';

CREATE OR REPLACE FUNCTION public.rg_products_balance(
	in_customer_ids integer[] DEFAULT NULL,
	in_customer_sale_place_ids integer[] DEFAULT NULL,
	in_product_ids integer[] DEFAULT NULL,
	in_measure_unit_ids integer[] DEFAULT NULL
)
RETURNS TABLE (
	customer_id integer,
	customer_sale_place_id integer,
	product_id integer,
	measure_unit_id integer,
	quant_required numeric(19, 4),
	quant numeric(19, 4)
)
LANGUAGE sql
STABLE
AS $function$
	SELECT
		balance.customer_id,
		balance.customer_sale_place_id,
		balance.product_id,
		balance.measure_unit_id,
		balance.quant_required,
		balance.quant
	FROM public.rg_products_current AS balance
	WHERE (
		in_customer_ids IS NULL
		OR cardinality(in_customer_ids) = 0
		OR balance.customer_id = ANY(in_customer_ids)
	)
	AND (
		in_customer_sale_place_ids IS NULL
		OR cardinality(in_customer_sale_place_ids) = 0
		OR balance.customer_sale_place_id = ANY(in_customer_sale_place_ids)
	)
	AND (
		in_product_ids IS NULL
		OR cardinality(in_product_ids) = 0
		OR balance.product_id = ANY(in_product_ids)
	)
	AND (
		in_measure_unit_ids IS NULL
		OR cardinality(in_measure_unit_ids) = 0
		OR balance.measure_unit_id = ANY(in_measure_unit_ids)
	)
	AND (balance.quant_required <> 0 OR balance.quant <> 0)
	ORDER BY
		balance.customer_id,
		balance.customer_sale_place_id,
		balance.product_id,
		balance.measure_unit_id;
$function$;

COMMENT ON FUNCTION public.rg_products_balance(integer[], integer[], integer[], integer[]) IS 'Returns fast current accumulated totals from the products register.';

CREATE OR REPLACE FUNCTION public.rg_products_balance(
	in_effective_at timestamptz,
	in_customer_ids integer[] DEFAULT NULL,
	in_customer_sale_place_ids integer[] DEFAULT NULL,
	in_product_ids integer[] DEFAULT NULL,
	in_measure_unit_ids integer[] DEFAULT NULL
)
RETURNS TABLE (
	customer_id integer,
	customer_sale_place_id integer,
	product_id integer,
	measure_unit_id integer,
	quant_required numeric(19, 4),
	quant numeric(19, 4)
)
LANGUAGE sql
STABLE
AS $function$
	WITH boundary AS (
		SELECT
			public.register_month_start(in_effective_at) AS period_start,
			public.register_month_start_at(in_effective_at) AS period_start_at
	), movements AS (
		SELECT
			period.customer_id,
			period.customer_sale_place_id,
			period.product_id,
			period.measure_unit_id,
			period.quant_required,
			period.quant
		FROM public.rg_products AS period
		CROSS JOIN boundary
		WHERE period.period_start < boundary.period_start
			AND (
				in_customer_ids IS NULL
				OR cardinality(in_customer_ids) = 0
				OR period.customer_id = ANY(in_customer_ids)
			)
			AND (
				in_customer_sale_place_ids IS NULL
				OR cardinality(in_customer_sale_place_ids) = 0
				OR period.customer_sale_place_id = ANY(in_customer_sale_place_ids)
			)
			AND (
				in_product_ids IS NULL
				OR cardinality(in_product_ids) = 0
				OR period.product_id = ANY(in_product_ids)
			)
			AND (
				in_measure_unit_ids IS NULL
				OR cardinality(in_measure_unit_ids) = 0
				OR period.measure_unit_id = ANY(in_measure_unit_ids)
			)

		UNION ALL

		SELECT
			action.customer_id,
			action.customer_sale_place_id,
			action.product_id,
			action.measure_unit_id,
			action.quant_required,
			action.quant
		FROM public.ra_products AS action
		CROSS JOIN boundary
		WHERE action.effective_at >= boundary.period_start_at
			AND action.effective_at <= in_effective_at
			AND (
				in_customer_ids IS NULL
				OR cardinality(in_customer_ids) = 0
				OR action.customer_id = ANY(in_customer_ids)
			)
			AND (
				in_customer_sale_place_ids IS NULL
				OR cardinality(in_customer_sale_place_ids) = 0
				OR action.customer_sale_place_id = ANY(in_customer_sale_place_ids)
			)
			AND (
				in_product_ids IS NULL
				OR cardinality(in_product_ids) = 0
				OR action.product_id = ANY(in_product_ids)
			)
			AND (
				in_measure_unit_ids IS NULL
				OR cardinality(in_measure_unit_ids) = 0
				OR action.measure_unit_id = ANY(in_measure_unit_ids)
			)
	)
	SELECT
		movements.customer_id,
		movements.customer_sale_place_id,
		movements.product_id,
		movements.measure_unit_id,
		SUM(movements.quant_required)::numeric(19, 4) AS quant_required,
		SUM(movements.quant)::numeric(19, 4) AS quant
	FROM movements
	GROUP BY
		movements.customer_id,
		movements.customer_sale_place_id,
		movements.product_id,
		movements.measure_unit_id
	HAVING SUM(movements.quant_required) <> 0 OR SUM(movements.quant) <> 0
	ORDER BY
		movements.customer_id,
		movements.customer_sale_place_id,
		movements.product_id,
		movements.measure_unit_id;
$function$;

COMMENT ON FUNCTION public.rg_products_balance(timestamptz, integer[], integer[], integer[], integer[]) IS 'Returns products register totals at an exact instant using completed monthly turnovers plus raw actions from the requested month.';

CREATE OR REPLACE VIEW public.product_register_recorders AS
SELECT
	'Order'::text AS recorder_type,
	orders.id::bigint AS recorder_id,
	orders.for_date AS document_date,
	orders.number_1c AS document_number
FROM public.orders AS orders;

COMMENT ON VIEW public.product_register_recorders IS 'Normalizes document headers used as ra_products recorders.';

COMMIT;
