BEGIN;

CREATE SCHEMA IF NOT EXISTS integration_1c;

CREATE TABLE integration_1c.jobs (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	command text NOT NULL,
	params jsonb NOT NULL DEFAULT 'null'::jsonb,
	correlation_id text,
	metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
	status text NOT NULL DEFAULT 'queued',
	priority integer NOT NULL DEFAULT 0,
	available_at timestamptz NOT NULL DEFAULT now(),
	attempt_count integer NOT NULL DEFAULT 0,
	max_attempts integer NOT NULL DEFAULT 5,
	locked_at timestamptz,
	locked_by text,
	last_error text,
	created_at timestamptz NOT NULL DEFAULT now(),
	updated_at timestamptz NOT NULL DEFAULT now(),
	started_at timestamptz,
	completed_at timestamptz,
	CONSTRAINT jobs_command_not_empty CHECK (btrim(command) <> ''),
	CONSTRAINT jobs_metadata_is_object CHECK (jsonb_typeof(metadata) = 'object'),
	CONSTRAINT jobs_status_check CHECK (status IN ('queued', 'processing', 'completed')),
	CONSTRAINT jobs_attempt_count_check CHECK (attempt_count >= 0),
	CONSTRAINT jobs_max_attempts_check CHECK (max_attempts > 0),
	CONSTRAINT jobs_attempt_count_max_check CHECK (attempt_count <= max_attempts)
);

CREATE INDEX jobs_ready_idx
	ON integration_1c.jobs (priority DESC, available_at, created_at, id)
	WHERE status = 'queued';

CREATE INDEX jobs_processing_idx
	ON integration_1c.jobs (locked_at, id)
	WHERE status = 'processing';

CREATE INDEX jobs_correlation_id_idx
	ON integration_1c.jobs (correlation_id)
	WHERE correlation_id IS NOT NULL;

CREATE TABLE integration_1c.attempts (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	job_id bigint NOT NULL REFERENCES integration_1c.jobs(id) ON DELETE CASCADE,
	attempt_no integer NOT NULL,
	worker_id text NOT NULL,
	started_at timestamptz NOT NULL DEFAULT now(),
	finished_at timestamptz,
	http_status integer,
	content_type text,
	response_headers jsonb,
	response_body bytea,
	response_body_size bigint,
	transport_error text,
	CONSTRAINT attempts_attempt_no_check CHECK (attempt_no > 0),
	CONSTRAINT attempts_http_status_check CHECK (http_status IS NULL OR http_status BETWEEN 100 AND 599),
	CONSTRAINT attempts_response_body_size_check CHECK (response_body_size IS NULL OR response_body_size >= 0),
	CONSTRAINT attempts_job_attempt_unique UNIQUE (job_id, attempt_no)
);

CREATE INDEX attempts_job_id_idx
	ON integration_1c.attempts (job_id, attempt_no DESC);

CREATE TABLE integration_1c.results (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	job_id bigint NOT NULL REFERENCES integration_1c.jobs(id) ON DELETE CASCADE,
	attempt_id bigint NOT NULL REFERENCES integration_1c.attempts(id) ON DELETE CASCADE,
	outcome text NOT NULL,
	http_status integer,
	content_type text,
	response_headers jsonb,
	body bytea,
	body_size bigint,
	transport_error text,
	created_at timestamptz NOT NULL DEFAULT now(),
	consumed_at timestamptz,
	consumed_by text,
	CONSTRAINT results_job_id_unique UNIQUE (job_id),
	CONSTRAINT results_outcome_check CHECK (outcome IN ('http_response', 'transport_error')),
	CONSTRAINT results_http_status_check CHECK (http_status IS NULL OR http_status BETWEEN 100 AND 599),
	CONSTRAINT results_body_size_check CHECK (body_size IS NULL OR body_size >= 0),
	CONSTRAINT results_outcome_fields_check CHECK (
		(outcome = 'http_response' AND http_status IS NOT NULL AND transport_error IS NULL)
		OR
		(outcome = 'transport_error' AND http_status IS NULL AND transport_error IS NOT NULL)
	)
);

CREATE INDEX results_unconsumed_idx
	ON integration_1c.results (created_at, id)
	WHERE consumed_at IS NULL;

CREATE OR REPLACE FUNCTION integration_1c.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
	NEW.updated_at := clock_timestamp();
	RETURN NEW;
END;
$$;

CREATE TRIGGER jobs_set_updated_at
BEFORE UPDATE ON integration_1c.jobs
FOR EACH ROW
EXECUTE FUNCTION integration_1c.set_updated_at();

CREATE OR REPLACE FUNCTION integration_1c.notify_insert()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
	PERFORM pg_notify(TG_ARGV[0], to_jsonb(NEW)->>'id');
	RETURN NEW;
END;
$$;

CREATE TRIGGER jobs_notify_insert
AFTER INSERT ON integration_1c.jobs
FOR EACH ROW
EXECUTE FUNCTION integration_1c.notify_insert('integration_1c_jobs');

CREATE TRIGGER results_notify_insert
AFTER INSERT ON integration_1c.results
FOR EACH ROW
EXECUTE FUNCTION integration_1c.notify_insert('integration_1c_results');

COMMENT ON SCHEMA integration_1c IS
	'Generic PostgreSQL-backed transport queue for 1C integration.';

COMMENT ON TABLE integration_1c.jobs IS
	'Commands awaiting generic execution by integration-1c-worker. params is opaque to the worker.';

COMMENT ON TABLE integration_1c.attempts IS
	'Technical history of every HTTP execution attempt.';

COMMENT ON TABLE integration_1c.results IS
	'One terminal opaque result per job. Business interpretation belongs to the project application.';

COMMENT ON COLUMN integration_1c.jobs.command IS
	'1C command name forwarded without interpretation.';

COMMENT ON COLUMN integration_1c.jobs.params IS
	'JSON value forwarded as the params member of the 1C request without domain parsing.';

COMMENT ON COLUMN integration_1c.results.outcome IS
	'http_response means an HTTP response was received; transport_error means no HTTP response was obtained.';

COMMENT ON COLUMN integration_1c.results.consumed_at IS
	'Optional project-consumer acknowledgement. The generic worker never changes this field.';

COMMIT;
