-- Code generated by cmd/codegen. Review before applying.

BEGIN;

ALTER TABLE public.order_items
	DROP CONSTRAINT IF EXISTS order_items_product_id_fkey;

DELETE FROM public.main_menus AS menu
USING public.application_routes AS route
WHERE menu.route_id = route.id
	AND menu.role_id = 'admin'
	AND menu.user_id IS NULL
	AND menu.caption = 'Продукция'
	AND route.name = 'products';

DELETE FROM public.main_menus AS parent
WHERE parent.role_id = 'admin'
	AND parent.user_id IS NULL
	AND parent.parent_id IS NULL
	AND parent.caption = 'Продукция'
	AND NOT EXISTS (
		SELECT 1
		FROM public.main_menus AS child
		WHERE child.parent_id = parent.id
	);

DELETE FROM public.application_routes AS route
WHERE route.name = 'products'
	AND NOT EXISTS (
		SELECT 1
		FROM public.main_menus AS menu
		WHERE menu.route_id = route.id
	);

DELETE FROM public.role_permissions
WHERE permission_code IN (
	'product.create',
	'product.list',
	'product.detail',
	'product.update',
	'product.delete'
);

DELETE FROM public.permissions
WHERE code IN (
	'product.create',
	'product.list',
	'product.detail',
	'product.update',
	'product.delete'
);

DROP TABLE IF EXISTS public.products;

COMMIT;
