-- Code generated by cmd/codegen. Review before applying.

BEGIN;

CREATE TABLE public.order_items (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	line_num integer NOT NULL,
	order_id integer NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE ON UPDATE CASCADE,
	product_id integer NOT NULL,
	measure_unit_id integer NOT NULL REFERENCES public.measure_units(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	quant_required numeric(19, 4) NOT NULL,
	quant numeric(19, 4) NOT NULL,
	CHECK (line_num > 0),
	CHECK (quant > 0)
);

COMMENT ON TABLE public.order_items IS 'order document lines.';
COMMENT ON COLUMN public.order_items.line_num IS 'Line number within the document.';
COMMENT ON COLUMN public.order_items.order_id IS 'Parent order document.';
COMMENT ON COLUMN public.order_items.product_id IS 'Product.';
COMMENT ON COLUMN public.order_items.measure_unit_id IS 'Measurement unit.';
COMMENT ON COLUMN public.order_items.quant_required IS 'Ordered product quantity.';
COMMENT ON COLUMN public.order_items.quant IS 'Product quantity.';

CREATE UNIQUE INDEX order_items_order_id_line_num_idx
	ON public.order_items USING btree (order_id, line_num);

WITH required(code, description) AS (
	VALUES
		('orderItem.list', 'Просмотр строк заказа'),
		('orderItem.detail', 'Просмотр строки заказа')
)
INSERT INTO public.permissions (code, description)
SELECT required.code, required.description
FROM required
ON CONFLICT (code) DO UPDATE
SET description = EXCLUDED.description;

WITH roles(role_id) AS (
	VALUES
		('admin'::public.role_types)
), required(permission_code) AS (
	VALUES
		('orderItem.list'),
		('orderItem.detail')
)
INSERT INTO public.role_permissions (role_id, permission_code)
SELECT roles.role_id, required.permission_code
FROM roles
CROSS JOIN required
ON CONFLICT DO NOTHING;

COMMIT;
