-- Code generated by cmd/codegen. Review before applying.

BEGIN;

CREATE TABLE public.orders (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	for_date date NOT NULL,
	number_1c text,
	ref_1c text,
	customer_id integer NOT NULL REFERENCES public.customers(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	customer_sale_place_id integer NOT NULL REFERENCES public.customer_sale_places(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	customer_user_id integer REFERENCES public.max_users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	status_id integer REFERENCES public.order_statuses(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	comment_customer text,
	comment_admin text
);

COMMENT ON TABLE public.orders IS 'Order reference data.';
COMMENT ON COLUMN public.orders.for_date IS 'Order for what date.';
COMMENT ON COLUMN public.orders.ref_1c IS 'Reference to 1c object.';
COMMENT ON COLUMN public.orders.customer_id IS 'Customer reference';
COMMENT ON COLUMN public.orders.customer_sale_place_id IS 'Customer sale place reference';
COMMENT ON COLUMN public.orders.customer_user_id IS 'Customer user reference';
COMMENT ON COLUMN public.orders.status_id IS 'Order status reference';

CREATE INDEX orders_for_date_idx
	ON public.orders USING btree (for_date);

CREATE INDEX orders_customer_id_idx
	ON public.orders USING btree (customer_id);

CREATE INDEX orders_number_1c_idx
	ON public.orders USING btree (number_1c);

CREATE INDEX orders_ref_1c_idx
	ON public.orders USING btree (ref_1c);

WITH required(code, description) AS (
	VALUES
		('order.create', 'Создание заказа'),
		('order.list', 'Просмотр списка заказов'),
		('order.detail', 'Просмотр заказа'),
		('order.update', 'Изменение заказа'),
		('order.delete', 'Удаление заказа')
)
INSERT INTO public.permissions (code, description)
SELECT required.code, required.description
FROM required
ON CONFLICT (code) DO UPDATE
SET description = EXCLUDED.description;

WITH roles(role_id) AS (
	VALUES
		('admin'::public.role_types)
), required(permission_code) AS (
	VALUES
		('order.create'),
		('order.list'),
		('order.detail'),
		('order.update'),
		('order.delete')
)
INSERT INTO public.role_permissions (role_id, permission_code)
SELECT roles.role_id, required.permission_code
FROM roles
CROSS JOIN required
ON CONFLICT DO NOTHING;

INSERT INTO public.application_routes (
	name,
	path,
	descr,
	section,
	icon,
	menu_available,
	is_active
)
VALUES (
	'orders',
	'/order',
	'Заказы',
	'Документы',
	'pi pi-truck',
	true,
	true
)
ON CONFLICT (name) DO UPDATE
SET
	path = EXCLUDED.path,
	descr = EXCLUDED.descr,
	section = EXCLUDED.descr,
	icon = EXCLUDED.icon,
	menu_available = EXCLUDED.menu_available,
	is_active = true;

INSERT INTO public.main_menus (
	role_id,
	caption,
	icon,
	sort_order,
	is_active
)
SELECT
	'admin'::public.role_types,
	'Заказы',
	NULL,
	40,
	true
WHERE NOT EXISTS (
	SELECT 1
	FROM public.main_menus AS existing
	WHERE existing.role_id = 'admin'::public.role_types
		AND existing.user_id IS NULL
		AND existing.parent_id IS NULL
		AND existing.caption = 'Заказы'
);

UPDATE public.main_menus
SET
	icon = NULL,
	sort_order = 40,
	is_active = true
WHERE role_id = 'admin'::public.role_types
	AND user_id IS NULL
	AND parent_id IS NULL
	AND caption = 'Заказы';

UPDATE public.main_menus AS existing
SET
	parent_id = (
		SELECT parent.id
		FROM public.main_menus AS parent
		WHERE parent.role_id = 'admin'::public.role_types
			AND parent.user_id IS NULL
			AND parent.parent_id IS NULL
			AND parent.caption = 'Заказы'
		ORDER BY parent.id
		LIMIT 1
	),
	caption = 'Заказы',
	icon = NULL,
	sort_order = 10,
	is_active = true
FROM public.application_routes AS route
WHERE route.name = 'orders'
	AND existing.role_id = 'admin'::public.role_types
	AND existing.user_id IS NULL
	AND existing.route_id = route.id
	AND EXISTS (
		SELECT 1
		FROM public.main_menus AS parent
		WHERE parent.role_id = 'admin'::public.role_types
			AND parent.user_id IS NULL
			AND parent.parent_id IS NULL
			AND parent.caption = 'Заказы'
	)
;

INSERT INTO public.main_menus (
	role_id,
	parent_id,
	caption,
	route_id,
	icon,
	sort_order,
	is_active
)
SELECT
	'admin'::public.role_types,
	parent.id,
	'Заказы',
	route.id,
	NULL,
	10,
	true
FROM public.application_routes AS route
JOIN LATERAL (
	SELECT item.id
	FROM public.main_menus AS item
	WHERE item.role_id = 'admin'::public.role_types
		AND item.user_id IS NULL
		AND item.parent_id IS NULL
		AND item.caption = 'Заказы'
	ORDER BY item.id
	LIMIT 1
) AS parent ON true
WHERE route.name = 'orders'
	AND NOT EXISTS (
		SELECT 1
		FROM public.main_menus AS existing
		WHERE existing.role_id = 'admin'::public.role_types
			AND existing.user_id IS NULL
			AND existing.route_id = route.id
	);

COMMIT;
