-- Code generated by cmd/codegen. Review before applying.

BEGIN;

CREATE TABLE public.customers (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	name text NOT NULL,
	inn varchar(12),
	kpp varchar(10),
	ref_1c varchar(36),
	is_active boolean NOT NULL DEFAULT true,
	CHECK (btrim(name) <> '')
);

COMMENT ON TABLE public.customers IS 'Customer reference data.';
COMMENT ON COLUMN public.customers.name IS 'Display name of the customer.';
COMMENT ON COLUMN public.customers.inn IS 'Customer INN.';
COMMENT ON COLUMN public.customers.kpp IS 'Customer KPP.';
COMMENT ON COLUMN public.customers.ref_1c IS 'Reference to 1c object.';

CREATE INDEX customers_name_idx
	ON public.customers USING btree (lower(name));

CREATE UNIQUE INDEX customers_inn_kpp_idx
	ON public.customers USING btree (inn, kpp);

CREATE UNIQUE INDEX customers_ref_1c_idx
	ON public.customers USING btree (ref_1c);

WITH required(code, description) AS (
	VALUES
		('customer.create', 'Создание покупателя'),
		('customer.list', 'Просмотр списка покупателей'),
		('customer.detail', 'Просмотр покупателя'),
		('customer.update', 'Изменение покупателя'),
		('customer.delete', 'Удаление покупателя')
)
INSERT INTO public.permissions (code, description)
SELECT required.code, required.description
FROM required
ON CONFLICT (code) DO UPDATE
SET description = EXCLUDED.description;

WITH roles(role_id) AS (
	VALUES
	('admin'::role_types)
), required(permission_code) AS (
	VALUES
		('customer.create'),
		('customer.list'),
		('customer.detail'),
		('customer.update'),
		('customer.delete')
)
INSERT INTO public.role_permissions (role_id, permission_code)
SELECT roles.role_id, required.permission_code
FROM roles
CROSS JOIN required
ON CONFLICT DO NOTHING;

INSERT INTO public.application_routes (
	name,
	path,
	descr,
	section,
	icon,
	menu_available,
	is_active
)
VALUES (
	'customers',
	'/customer',
	'Покупатели',
	'Справочники',
	'pi pi-users',
	true,
	true
)
ON CONFLICT (name) DO UPDATE
SET
	path = EXCLUDED.path,
	descr = EXCLUDED.descr,
	section = EXCLUDED.section,
	icon = EXCLUDED.icon,
	menu_available = EXCLUDED.menu_available,
	is_active = true;

INSERT INTO public.main_menus (
	role_id,
	caption,
	icon,
	sort_order,
	is_active
)
SELECT
'admin'::role_types,
	'Покупатели',
	NULL,
	40,
	true
WHERE NOT EXISTS (
	SELECT 1
	FROM public.main_menus AS existing
	WHERE existing.role_id = 'admin'
		AND existing.user_id IS NULL
		AND existing.parent_id IS NULL
		AND existing.caption = 'Покупатели'
);

UPDATE public.main_menus
SET
	icon = NULL,
	sort_order = 40,
	is_active = true
WHERE role_id = 'admin'
	AND user_id IS NULL
	AND parent_id IS NULL
	AND caption = 'Покупатели';

UPDATE public.main_menus AS existing
SET
	parent_id = (
		SELECT parent.id
		FROM public.main_menus AS parent
		WHERE parent.role_id = 'admin'
			AND parent.user_id IS NULL
			AND parent.parent_id IS NULL
			AND parent.caption = 'Покупатели'
		ORDER BY parent.id
		LIMIT 1
	),
	caption = 'Покупатели',
	icon = NULL,
	sort_order = 10,
	is_active = true
FROM public.application_routes AS route
WHERE route.name = 'customers'
	AND existing.role_id = 'admin'
	AND existing.user_id IS NULL
	AND existing.route_id = route.id
	AND EXISTS (
		SELECT 1
		FROM public.main_menus AS parent
		WHERE parent.role_id = 'admin'
			AND parent.user_id IS NULL
			AND parent.parent_id IS NULL
			AND parent.caption = 'Покупатели'
	)
;

INSERT INTO public.main_menus (
	role_id,
	parent_id,
	caption,
	route_id,
	icon,
	sort_order,
	is_active
)
SELECT
	'admin',
	parent.id,
	'Покупатели',
	route.id,
	NULL,
	10,
	true
FROM public.application_routes AS route
JOIN LATERAL (
	SELECT item.id
	FROM public.main_menus AS item
	WHERE item.role_id = 'admin'
		AND item.user_id IS NULL
		AND item.parent_id IS NULL
		AND item.caption = 'Покупатели'
	ORDER BY item.id
	LIMIT 1
) AS parent ON true
WHERE route.name = 'customers'
	AND NOT EXISTS (
		SELECT 1
		FROM public.main_menus AS existing
		WHERE existing.role_id = 'admin'
			AND existing.user_id IS NULL
			AND existing.route_id = route.id
	);

COMMIT;
