BEGIN;

CREATE TABLE public.notification_templates (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	code text NOT NULL,
	event text NOT NULL,
	body_template text NOT NULL,
	is_active boolean NOT NULL DEFAULT TRUE,
	CONSTRAINT notification_templates_code_not_empty CHECK (btrim(code) <> ''),
	CONSTRAINT notification_templates_event_not_empty CHECK (btrim(event) <> ''),
	CONSTRAINT notification_templates_body_not_empty CHECK (btrim(body_template) <> ''),
	CONSTRAINT notification_templates_code_key UNIQUE (code)
);

COMMENT ON TABLE public.notification_templates IS
	'Editable templates used to render application notifications.';
COMMENT ON COLUMN public.notification_templates.code IS
	'Stable unique template code.';
COMMENT ON COLUMN public.notification_templates.event IS
	'Domain event that selects the template, for example order.created.';
COMMENT ON COLUMN public.notification_templates.body_template IS
	'Go text/template message body.';

CREATE INDEX notification_templates_event_active_idx
	ON public.notification_templates (event, id)
	WHERE is_active;

CREATE TABLE public.notification_template_recipients (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	template_id integer NOT NULL REFERENCES public.notification_templates(id) ON DELETE CASCADE ON UPDATE CASCADE,
	user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT notification_template_recipients_template_user_key UNIQUE (template_id, user_id)
);

COMMENT ON TABLE public.notification_template_recipients IS
	'Internal application users that receive notifications rendered by a template.';
COMMENT ON COLUMN public.notification_template_recipients.user_id IS
	'Application user. Its users.max_user_id binding resolves the MAX account at enqueue time.';

CREATE INDEX notification_template_recipients_user_idx
	ON public.notification_template_recipients (user_id, template_id);

CREATE OR REPLACE FUNCTION public.notification_templates_ref(notification_templates)
RETURNS json
LANGUAGE sql
VOLATILE
AS $$
	SELECT CASE
		WHEN $1.id IS NULL THEN NULL
		ELSE json_build_object(
			'keys', json_build_object('id', $1.id),
			'descr', $1.code,
			'dataType', 'notification_templates'
		)
	END;
$$;

CREATE OR REPLACE VIEW public.notification_template_recipients_list AS
SELECT
	r.id,
	r.template_id,
	public.notification_templates_ref(t) AS template,
	r.user_id,
	public.users_ref(u) AS "user"
FROM public.notification_template_recipients AS r
JOIN public.notification_templates AS t ON t.id = r.template_id
JOIN public.users AS u ON u.id = r.user_id;

CREATE OR REPLACE VIEW public.notification_template_recipients_detail AS
SELECT
	r.id,
	r.template_id,
	public.notification_templates_ref(t) AS template,
	r.user_id,
	public.users_ref(u) AS "user"
FROM public.notification_template_recipients AS r
JOIN public.notification_templates AS t ON t.id = r.template_id
JOIN public.users AS u ON u.id = r.user_id;

INSERT INTO public.notification_templates (code, event, body_template, is_active)
VALUES
	(
		'order_submitted',
		'order.submitted',
		E'{{if .Resubmitted}}Заказ №{{.OrderID}} изменён клиентом{{else}}Новый заказ №{{.OrderID}}{{end}}\nКлиент: {{.CustomerName}}\nТочка продажи: {{.SalePlaceName}}\nДата: {{.ForDate}}{{if .CommentCustomer}}\nКомментарий: {{.CommentCustomer}}{{end}}',
		TRUE
	),
	(
		'order_changed',
		'order.changed',
		E'Ваш заказ №{{.OrderID}} изменён.{{if .StatusChanged}}\nСтатус: {{.StatusName}}{{end}}{{if .ChangedItems}}\nИзменено количество:\n{{.ChangedItems}}{{end}}',
		TRUE
	)
ON CONFLICT (code) DO NOTHING;

INSERT INTO public.permissions (code, description)
VALUES
	('notificationTemplate.create', 'Создание шаблонов уведомлений'),
	('notificationTemplate.list', 'Просмотр шаблонов уведомлений'),
	('notificationTemplate.detail', 'Просмотр шаблона уведомления'),
	('notificationTemplate.update', 'Изменение шаблонов уведомлений'),
	('notificationTemplate.delete', 'Удаление шаблонов уведомлений'),
	('notificationTemplateRecipient.create', 'Добавление получателей уведомлений'),
	('notificationTemplateRecipient.list', 'Просмотр получателей уведомлений'),
	('notificationTemplateRecipient.detail', 'Просмотр получателя уведомлений'),
	('notificationTemplateRecipient.update', 'Изменение получателей уведомлений'),
	('notificationTemplateRecipient.delete', 'Удаление получателей уведомлений')
ON CONFLICT (code) DO UPDATE SET description = EXCLUDED.description;

INSERT INTO public.role_permissions (role_id, permission_code)
SELECT 'admin'::public.role_types, p.code
FROM public.permissions AS p
WHERE p.code IN (
	'notificationTemplate.create',
	'notificationTemplate.list',
	'notificationTemplate.detail',
	'notificationTemplate.update',
	'notificationTemplate.delete',
	'notificationTemplateRecipient.create',
	'notificationTemplateRecipient.list',
	'notificationTemplateRecipient.detail',
	'notificationTemplateRecipient.update',
	'notificationTemplateRecipient.delete'
)
ON CONFLICT DO NOTHING;

COMMIT;
