// Code generated by cmd/codegen. DO NOT EDIT.

package services

import (
	"context"
	"errors"
	"fmt"

	"github.com/dronm/ds/v4"
	"github.com/dronm/meatshop/internal/apperrors"
	"github.com/dronm/meatshop/internal/models"
	"github.com/dronm/modelbind"
	"github.com/dronm/modelbind/types"
	"github.com/dronm/session"
	"github.com/dronm/webapp"
	wmodels "github.com/dronm/webapp/models"
)

type CustomerSalePlaceService struct {
	DB      ds.Provider
	Session session.Session
	QueryID string
}

func NewCustomerSalePlaceService(ctx webapp.ServiceContext) any {
	return &CustomerSalePlaceService{
		DB:      ctx.DB,
		Session: ctx.Session,
		QueryID: ctx.QueryID,
	}
}

func RegisterCustomerSalePlaceService() {
	webapp.MustRegisterService(
		"CustomerSalePlace",
		&CustomerSalePlaceService{},
		NewCustomerSalePlaceService,
		webapp.WithCRUDNotifications(),
	)
}

func (s *CustomerSalePlaceService) Create(
	ctx context.Context,
	input modelbind.ModelInput[*models.CustomerSalePlace],
) (map[string]any, error) {
	if err := s.requireSession(); err != nil {
		return nil, err
	}
	if err := s.requireDB(); err != nil {
		return nil, err
	}

	result, err := webapp.InsertModelInput(ctx, s.DB, input, nil)
	if err != nil {
		return nil, fmt.Errorf("insert Customer sale place: %w", err)
	}

	return result, nil
}

func (s *CustomerSalePlaceService) Update(
	ctx context.Context,
	input webapp.UpdateByKeysInput[*models.CustomerSalePlaceKey, *models.CustomerSalePlace],
) (wmodels.RowsAffectedResponse, error) {
	if err := s.requireSession(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if input.Keys == nil {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("Customer sale place key is required", nil)
	}
	if input.Keys.ID <= 0 {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("Customer sale place id is required", nil)
	}

	rowsAffected, err := webapp.UpdateModelInput(ctx, s.DB, input.Keys, input.Input, nil)
	if err != nil {
		return wmodels.RowsAffectedResponse{}, fmt.Errorf("update Customer sale place: %w", err)
	}
	if rowsAffected == 0 {
		return wmodels.RowsAffectedResponse{}, webapp.NotFound(
			"Customer sale place not found",
			map[string]any{
				"id": input.Keys.ID,
			},
		)
	}

	return wmodels.RowsAffectedResponse{RowsAffected: rowsAffected}, nil
}

func (s *CustomerSalePlaceService) Delete(
	ctx context.Context,
	id int,
) (wmodels.RowsAffectedResponse, error) {
	if err := s.requireSession(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if id <= 0 {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("Customer sale place id is required", nil)
	}

	rowsAffected, err := webapp.DeleteModel(
		ctx,
		s.DB,
		[]types.DBModel{
			models.CustomerSalePlaceKey{
				ID: id,
			},
		},
		nil,
	)
	if err != nil {
		return wmodels.RowsAffectedResponse{}, fmt.Errorf("delete Customer sale place: %w", err)
	}
	if rowsAffected == 0 {
		return wmodels.RowsAffectedResponse{}, webapp.NotFound(
			"Customer sale place not found",
			map[string]any{
				"id": id,
			},
		)
	}

	return wmodels.RowsAffectedResponse{RowsAffected: rowsAffected}, nil
}

func (s *CustomerSalePlaceService) Detail(
	ctx context.Context,
	id int,
) (*models.CustomerSalePlace, error) {
	if err := s.requireSession(); err != nil {
		return nil, err
	}
	if err := s.requireDB(); err != nil {
		return nil, err
	}
	if id <= 0 {
		return nil, webapp.BadRequest("Customer sale place id is required", nil)
	}

	result, err := webapp.FetchModel(
		ctx,
		s.DB,
		models.CustomerSalePlaceKey{
			ID: id,
		},
		&models.CustomerSalePlace{},
	)
	if err != nil {
		if errors.Is(err, ds.ErrNoRows) {
			return nil, webapp.NotFound(
				"Customer sale place not found",
				map[string]any{
					"id": id,
				},
			)
		}
		return nil, fmt.Errorf("fetch Customer sale place: %w", err)
	}

	return result, nil
}

func (s *CustomerSalePlaceService) List(
	ctx context.Context,
	params modelbind.CollectionParams,
) (wmodels.CollectionResponse[*models.CustomerSalePlaceList], error) {
	if err := s.requireSession(); err != nil {
		return wmodels.CollectionResponse[*models.CustomerSalePlaceList]{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.CollectionResponse[*models.CustomerSalePlaceList]{}, err
	}

	rows, total, err := webapp.FetchCollectionModel(ctx, s.DB, &models.CustomerSalePlaceList{}, params)
	if err != nil {
		return wmodels.CollectionResponse[*models.CustomerSalePlaceList]{}, fmt.Errorf(
			"fetch Customer sale place collection: %w",
			err,
		)
	}

	return wmodels.CollectionResponse[*models.CustomerSalePlaceList]{
		Rows: rows,
		Agg:  total,
	}, nil
}

func (s *CustomerSalePlaceService) requireSession() error {
	if s.Session == nil {
		return apperrors.SessionRequired()
	}

	return nil
}

func (s *CustomerSalePlaceService) requireDB() error {
	if s.DB == nil {
		return webapp.Internal("database is not initialized", nil)
	}

	return nil
}
