// Code generated by cmd/codegen. DO NOT EDIT.

package services

import (
	"context"
	"errors"
	"fmt"

	"github.com/dronm/ds/v4"
	"github.com/dronm/meatshop/internal/apperrors"
	"github.com/dronm/meatshop/internal/models"
	"github.com/dronm/modelbind"
	"github.com/dronm/session"
	"github.com/dronm/webapp"
	wmodels "github.com/dronm/webapp/models"
)

type MaxInMessageService struct {
	DB      ds.Provider
	Session session.Session
	QueryID string
}

func NewMaxInMessageService(ctx webapp.ServiceContext) any {
	return &MaxInMessageService{
		DB:      ctx.DB,
		Session: ctx.Session,
		QueryID: ctx.QueryID,
	}
}

func RegisterMaxInMessageService() {
	webapp.MustRegisterService(
		"MaxInMessage",
		&MaxInMessageService{},
		NewMaxInMessageService,
	)
}

func (s *MaxInMessageService) Detail(
	ctx context.Context,
	id int64,
) (*models.MaxInMessage, error) {
	if err := s.requireSession(); err != nil {
		return nil, err
	}
	if err := s.requireDB(); err != nil {
		return nil, err
	}
	if id <= 0 {
		return nil, webapp.BadRequest("incoming MAX message id is required", nil)
	}

	result, err := webapp.FetchModel(
		ctx,
		s.DB,
		models.MaxInMessageKey{
			ID: id,
		},
		&models.MaxInMessage{},
	)
	if err != nil {
		if errors.Is(err, ds.ErrNoRows) {
			return nil, webapp.NotFound(
				"incoming MAX message not found",
				map[string]any{
					"id": id,
				},
			)
		}
		return nil, fmt.Errorf("fetch incoming MAX message: %w", err)
	}

	return result, nil
}

func (s *MaxInMessageService) List(
	ctx context.Context,
	params modelbind.CollectionParams,
) (wmodels.CollectionResponse[*models.MaxInMessageList], error) {
	if err := s.requireSession(); err != nil {
		return wmodels.CollectionResponse[*models.MaxInMessageList]{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.CollectionResponse[*models.MaxInMessageList]{}, err
	}

	rows, total, err := webapp.FetchCollectionModel(ctx, s.DB, &models.MaxInMessageList{}, params)
	if err != nil {
		return wmodels.CollectionResponse[*models.MaxInMessageList]{}, fmt.Errorf(
			"fetch incoming MAX message collection: %w",
			err,
		)
	}

	return wmodels.CollectionResponse[*models.MaxInMessageList]{
		Rows: rows,
		Agg:  total,
	}, nil
}

func (s *MaxInMessageService) requireSession() error {
	if s.Session == nil {
		return apperrors.SessionRequired()
	}

	return nil
}

func (s *MaxInMessageService) requireDB() error {
	if s.DB == nil {
		return webapp.Internal("database is not initialized", nil)
	}

	return nil
}
