// Code generated by cmd/codegen. DO NOT EDIT.

package services

import (
	"context"
	"errors"
	"fmt"

	"github.com/dronm/ds/v4"
	"github.com/dronm/meatshop/internal/apperrors"
	"github.com/dronm/meatshop/internal/models"
	"github.com/dronm/modelbind"
	"github.com/dronm/session"
	"github.com/dronm/webapp"
	wmodels "github.com/dronm/webapp/models"
)

type MaxOutMessageService struct {
	DB      ds.Provider
	Session session.Session
	QueryID string
}

func NewMaxOutMessageService(ctx webapp.ServiceContext) any {
	return &MaxOutMessageService{
		DB:      ctx.DB,
		Session: ctx.Session,
		QueryID: ctx.QueryID,
	}
}

func RegisterMaxOutMessageService() {
	webapp.MustRegisterService(
		"MaxOutMessage",
		&MaxOutMessageService{},
		NewMaxOutMessageService,
	)
}

func (s *MaxOutMessageService) Detail(
	ctx context.Context,
	id int64,
) (*models.MaxOutMessage, error) {
	if err := s.requireSession(); err != nil {
		return nil, err
	}
	if err := s.requireDB(); err != nil {
		return nil, err
	}
	if id <= 0 {
		return nil, webapp.BadRequest("outgoing MAX message id is required", nil)
	}

	result, err := webapp.FetchModel(
		ctx,
		s.DB,
		models.MaxOutMessageKey{
			ID: id,
		},
		&models.MaxOutMessage{},
	)
	if err != nil {
		if errors.Is(err, ds.ErrNoRows) {
			return nil, webapp.NotFound(
				"outgoing MAX message not found",
				map[string]any{
					"id": id,
				},
			)
		}
		return nil, fmt.Errorf("fetch outgoing MAX message: %w", err)
	}

	return result, nil
}

func (s *MaxOutMessageService) List(
	ctx context.Context,
	params modelbind.CollectionParams,
) (wmodels.CollectionResponse[*models.MaxOutMessageList], error) {
	if err := s.requireSession(); err != nil {
		return wmodels.CollectionResponse[*models.MaxOutMessageList]{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.CollectionResponse[*models.MaxOutMessageList]{}, err
	}

	rows, total, err := webapp.FetchCollectionModel(ctx, s.DB, &models.MaxOutMessageList{}, params)
	if err != nil {
		return wmodels.CollectionResponse[*models.MaxOutMessageList]{}, fmt.Errorf(
			"fetch outgoing MAX message collection: %w",
			err,
		)
	}

	return wmodels.CollectionResponse[*models.MaxOutMessageList]{
		Rows: rows,
		Agg:  total,
	}, nil
}

func (s *MaxOutMessageService) requireSession() error {
	if s.Session == nil {
		return apperrors.SessionRequired()
	}

	return nil
}

func (s *MaxOutMessageService) requireDB() error {
	if s.DB == nil {
		return webapp.Internal("database is not initialized", nil)
	}

	return nil
}
