// Code generated by cmd/codegen. DO NOT EDIT.

package services

import (
	"context"
	"fmt"

	"github.com/dronm/ds/v4"
	"github.com/dronm/meatshop/internal/apperrors"
	"github.com/dronm/meatshop/internal/models"
	"github.com/dronm/modelbind"
	"github.com/dronm/session"
	"github.com/dronm/webapp"
	wmodels "github.com/dronm/webapp/models"
)

type OrderService struct {
	DB      ds.Provider
	Session session.Session
	QueryID string
}

func NewOrderService(ctx webapp.ServiceContext) any {
	return &OrderService{
		DB:      ctx.DB,
		Session: ctx.Session,
		QueryID: ctx.QueryID,
	}
}

func RegisterOrderService() {
	webapp.MustRegisterService(
		"Order",
		&OrderService{},
		NewOrderService,
		webapp.WithCRUDNotifications(),
	)
}

func (s *OrderService) List(
	ctx context.Context,
	params modelbind.CollectionParams,
) (wmodels.CollectionResponse[*models.OrderList], error) {
	if err := s.requireSession(); err != nil {
		return wmodels.CollectionResponse[*models.OrderList]{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.CollectionResponse[*models.OrderList]{}, err
	}

	rows, total, err := webapp.FetchCollectionModel(ctx, s.DB, &models.OrderList{}, params)
	if err != nil {
		return wmodels.CollectionResponse[*models.OrderList]{}, fmt.Errorf(
			"fetch order collection: %w",
			err,
		)
	}

	return wmodels.CollectionResponse[*models.OrderList]{
		Rows: rows,
		Agg:  total,
	}, nil
}

func (s *OrderService) requireSession() error {
	if s.Session == nil {
		return apperrors.SessionRequired()
	}

	return nil
}

func (s *OrderService) requireDB() error {
	if s.DB == nil {
		return webapp.Internal("database is not initialized", nil)
	}

	return nil
}
