// Code generated by cmd/codegen. DO NOT EDIT.

package services

import (
	"context"
	"errors"
	"fmt"

	"github.com/dronm/ds/v4"
	"github.com/dronm/meatshop/internal/apperrors"
	"github.com/dronm/meatshop/internal/models"
	"github.com/dronm/modelbind"
	"github.com/dronm/session"
	"github.com/dronm/webapp"
	wmodels "github.com/dronm/webapp/models"
)

type OrderItemService struct {
	DB      ds.Provider
	Session session.Session
	QueryID string
}

func NewOrderItemService(ctx webapp.ServiceContext) any {
	return &OrderItemService{
		DB:      ctx.DB,
		Session: ctx.Session,
		QueryID: ctx.QueryID,
	}
}

func RegisterOrderItemService() {
	webapp.MustRegisterService(
		"OrderItem",
		&OrderItemService{},
		NewOrderItemService,
	)
}

func (s *OrderItemService) Detail(
	ctx context.Context,
	id int,
) (*models.OrderItem, error) {
	if err := s.requireSession(); err != nil {
		return nil, err
	}
	if err := s.requireDB(); err != nil {
		return nil, err
	}
	if id <= 0 {
		return nil, webapp.BadRequest("order item id is required", nil)
	}

	result, err := webapp.FetchModel(
		ctx,
		s.DB,
		models.OrderItemKey{
			ID: id,
		},
		&models.OrderItem{},
	)
	if err != nil {
		if errors.Is(err, ds.ErrNoRows) {
			return nil, webapp.NotFound(
				"order item not found",
				map[string]any{
					"id": id,
				},
			)
		}
		return nil, fmt.Errorf("fetch order item: %w", err)
	}

	return result, nil
}

func (s *OrderItemService) List(
	ctx context.Context,
	params modelbind.CollectionParams,
) (wmodels.CollectionResponse[*models.OrderItem], error) {
	if err := s.requireSession(); err != nil {
		return wmodels.CollectionResponse[*models.OrderItem]{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.CollectionResponse[*models.OrderItem]{}, err
	}

	rows, total, err := webapp.FetchCollectionModel(ctx, s.DB, &models.OrderItem{}, params)
	if err != nil {
		return wmodels.CollectionResponse[*models.OrderItem]{}, fmt.Errorf(
			"fetch order item collection: %w",
			err,
		)
	}

	return wmodels.CollectionResponse[*models.OrderItem]{
		Rows: rows,
		Agg:  total,
	}, nil
}

func (s *OrderItemService) requireSession() error {
	if s.Session == nil {
		return apperrors.SessionRequired()
	}

	return nil
}

func (s *OrderItemService) requireDB() error {
	if s.DB == nil {
		return webapp.Internal("database is not initialized", nil)
	}

	return nil
}
