// Code generated by cmd/codegen. DO NOT EDIT.

package services

import (
	"context"
	"errors"
	"fmt"

	"github.com/dronm/ds/v4"
	"github.com/dronm/meatshop/internal/apperrors"
	"github.com/dronm/meatshop/internal/models"
	"github.com/dronm/modelbind"
	"github.com/dronm/modelbind/types"
	"github.com/dronm/session"
	"github.com/dronm/webapp"
	wmodels "github.com/dronm/webapp/models"
)

type OrderCalendarDayService struct {
	DB      ds.Provider
	Session session.Session
	QueryID string
}

func NewOrderCalendarDayService(ctx webapp.ServiceContext) any {
	return &OrderCalendarDayService{
		DB:      ctx.DB,
		Session: ctx.Session,
		QueryID: ctx.QueryID,
	}
}

func RegisterOrderCalendarDayService() {
	webapp.MustRegisterService(
		"OrderCalendarDay",
		&OrderCalendarDayService{},
		NewOrderCalendarDayService,
		webapp.WithCRUDNotifications(),
	)
}

func (s *OrderCalendarDayService) Create(
	ctx context.Context,
	input modelbind.ModelInput[*models.OrderCalendarDay],
) (map[string]any, error) {
	if err := s.requireSession(); err != nil {
		return nil, err
	}
	if err := s.requireDB(); err != nil {
		return nil, err
	}

	result, err := webapp.InsertModelInput(ctx, s.DB, input, nil)
	if err != nil {
		return nil, fmt.Errorf("insert order calendar day: %w", err)
	}

	return result, nil
}

func (s *OrderCalendarDayService) Update(
	ctx context.Context,
	input webapp.UpdateByKeysInput[*models.OrderCalendarDayKey, *models.OrderCalendarDay],
) (wmodels.RowsAffectedResponse, error) {
	if err := s.requireSession(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if input.Keys == nil {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("order calendar day key is required", nil)
	}
	if input.Keys.ID <= 0 {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("order calendar day id is required", nil)
	}

	rowsAffected, err := webapp.UpdateModelInput(ctx, s.DB, input.Keys, input.Input, nil)
	if err != nil {
		return wmodels.RowsAffectedResponse{}, fmt.Errorf("update order calendar day: %w", err)
	}
	if rowsAffected == 0 {
		return wmodels.RowsAffectedResponse{}, webapp.NotFound(
			"order calendar day not found",
			map[string]any{
				"id": input.Keys.ID,
			},
		)
	}

	return wmodels.RowsAffectedResponse{RowsAffected: rowsAffected}, nil
}

func (s *OrderCalendarDayService) Delete(
	ctx context.Context,
	id int,
) (wmodels.RowsAffectedResponse, error) {
	if err := s.requireSession(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.RowsAffectedResponse{}, err
	}
	if id <= 0 {
		return wmodels.RowsAffectedResponse{}, webapp.BadRequest("order calendar day id is required", nil)
	}

	rowsAffected, err := webapp.DeleteModel(
		ctx,
		s.DB,
		[]types.DBModel{
			models.OrderCalendarDayKey{
				ID: id,
			},
		},
		nil,
	)
	if err != nil {
		return wmodels.RowsAffectedResponse{}, fmt.Errorf("delete order calendar day: %w", err)
	}
	if rowsAffected == 0 {
		return wmodels.RowsAffectedResponse{}, webapp.NotFound(
			"order calendar day not found",
			map[string]any{
				"id": id,
			},
		)
	}

	return wmodels.RowsAffectedResponse{RowsAffected: rowsAffected}, nil
}

func (s *OrderCalendarDayService) Detail(
	ctx context.Context,
	id int,
) (*models.OrderCalendarDay, error) {
	if err := s.requireSession(); err != nil {
		return nil, err
	}
	if err := s.requireDB(); err != nil {
		return nil, err
	}
	if id <= 0 {
		return nil, webapp.BadRequest("order calendar day id is required", nil)
	}

	result, err := webapp.FetchModel(
		ctx,
		s.DB,
		models.OrderCalendarDayKey{
			ID: id,
		},
		&models.OrderCalendarDay{},
	)
	if err != nil {
		if errors.Is(err, ds.ErrNoRows) {
			return nil, webapp.NotFound(
				"order calendar day not found",
				map[string]any{
					"id": id,
				},
			)
		}
		return nil, fmt.Errorf("fetch order calendar day: %w", err)
	}

	return result, nil
}

func (s *OrderCalendarDayService) List(
	ctx context.Context,
	params modelbind.CollectionParams,
) (wmodels.CollectionResponse[*models.OrderCalendarDay], error) {
	if err := s.requireSession(); err != nil {
		return wmodels.CollectionResponse[*models.OrderCalendarDay]{}, err
	}
	if err := s.requireDB(); err != nil {
		return wmodels.CollectionResponse[*models.OrderCalendarDay]{}, err
	}

	rows, total, err := webapp.FetchCollectionModel(ctx, s.DB, &models.OrderCalendarDay{}, params)
	if err != nil {
		return wmodels.CollectionResponse[*models.OrderCalendarDay]{}, fmt.Errorf(
			"fetch order calendar day collection: %w",
			err,
		)
	}

	return wmodels.CollectionResponse[*models.OrderCalendarDay]{
		Rows: rows,
		Agg:  total,
	}, nil
}

func (s *OrderCalendarDayService) requireSession() error {
	if s.Session == nil {
		return apperrors.SessionRequired()
	}

	return nil
}

func (s *OrderCalendarDayService) requireDB() error {
	if s.DB == nil {
		return webapp.Internal("database is not initialized", nil)
	}

	return nil
}
