// Code generated by cmd/codegen. DO NOT EDIT.

package services

func RegisterGeneratedServices() {
	RegisterCustomerService()
	RegisterCustomerSalePlaceService()
	RegisterMaxInMessageService()
	RegisterMaxOutMessageService()
	RegisterMaxUserService()
	RegisterMeasureUnitService()
	RegisterOrderService()
	RegisterOrderCalendarDayService()
	RegisterOrderItemService()
	RegisterProductService()
}
