-- SUPERUSER CODE
CREATE USER meatshop WITH PASSWORD '159753';
CREATE DATABASE meatshop OWNER meatshop;

ALTER SCHEMA public OWNER TO meatshop;
GRANT ALL ON SCHEMA public TO meatshop;
GRANT ALL PRIVILEGES ON DATABASE meatshop TO meatshop;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO meatshop;
CREATE EXTENSION pgcrypto;
CREATE EXTENSION pg_trgm; 

